### ISSUE TITLE
Do we need a way (RPC) to manually trigger a sync ?

### ISSUE THREAD

**Issue by karimra** [sdcio/data-server#37]
Do we need a way (RPC) to manually trigger a sync ?
This would be needed for periodic syncs (not on change)

**Comment by henderiw** [comment]
options:
- use gnmi-sync
- use sync per intent update: heavy but reliable -> auto sync flag in connectionProfile
- write back to the cache w/o device feedback: 2 source of truth

**Comment by henderiw** [comment]
Discussion on sync:
- seems the least common denominator for sync is a periodic fetch of the config for both netconf and gnmi

The result is:
- implement gnmi Get for gnmi using periodic sync: @steiler 
- implement pruning for gnmi - similar how netconf does this: @steiler 
- write back to the running config if the target accepts the change: @karimra 
- report sync issues that can be used at the upper layers for determining what to do: @karimra 
- config-server @henderiw

**Comment by steiler** [comment]
@henderiw close? or what are the open topics here?
