### ISSUE TITLE
properly handle choice/case syncing

### ISSUE THREAD

**Issue by karimra** [sdcio/data-server#70]
When using gNMI to sync, updates to a leaf with a parent being a YANG case needs to include deletion of other YANG cases from the cache

**Comment by karimra** [comment]
This is not needed as long as there is an on-change subscription as part of the sync strategy.

**Comment by steiler** [comment]
@henderiw I think we can close this... We've defined running als the lowest precedence, we do calculate the active cases as part of the tree building. So I assume it is mainly fine.
